### ISSUE TITLE
Update or replace django-braces

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#23] opened 2021-07-27 11:20 UTC
We use the package [django-braces](https://github.com/brack3t/django-braces) in edx/edx-analytics-dashboard. This package was last released in 2019 and it hasn't yet added support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by jmbowman** [comment] 2021-08-30 18:40
I think she's still out for another day or two, but I can go ahead and assign it to you.  Thanks for looking into this!

**Comment by natabene** [comment] 2021-09-15 16:23
Was closed as a duplicate of https://github.com/edx/upgrades/issues/23

**Comment by natabene** [comment] 2021-09-15 17:04
@magajh Just checking if you had a chance to look into this.

**Comment by magajh** [comment] 2021-09-17 19:45
Hi @natabene! 
A [PR](https://github.com/brack3t/django-braces/pull/265 that adds support for Django 3.2 was opened a while ago, all the tests seem to be passing just fine.  I opened a new [issue](https://github.com/brack3t/django-braces/issues/268) asking the supporters for a review on it. I'll keep you updated

**Comment by natabene** [comment] 2021-09-20 14:18
@magajh Thanks so much for an update and for your help!

**Comment by natabene** [comment] 2021-11-09 15:08
Do we have a release by any chance?

**Comment by UsamaSadiq** [comment] 2022-01-17 13:03
`Django-braces` [1.15.0](https://github.com/brack3t/django-braces/releases/tag/v1.15.0) was released with `Django 3.2` support which is now being [used](https://github.com/openedx/edx-analytics-dashboard/blob/c776647768d3bb75417c9f5d4c4970dd0c7bee1d/requirements/base.txt#L49) in `openedx/edx-analytics-dashboard`.
Marking this as Done and closing the issue now. 
@magajh thanks for your help on this issue.

**Closed by UsamaSadiq** 2022-01-17 13:03 UTC
Labels: outdated dependency
