### ISSUE TITLE
Update or replace django-classy-tags

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#39] opened 2021-07-27 14:13 UTC
We use the package [django-classy-tags](https://github.com/ojii/django-classy-tags) in edx/django-wiki, edx/edx-platform. It hasn't yet added support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by mariajgrimaldi** [comment] 2021-08-31 13:16
I'll be looking into this one! :100:

**Comment by natabene** [comment] 2021-09-02 02:42
@mariajgrimaldi Thank you so much, I appreciate! Please update us on your progress here.

**Comment by mariajgrimaldi** [comment] 2021-09-10 13:22
Hey! Sorry for the delay. 

I searched for _classytags_ on edx-platform -[here](https://github.com/edx/edx-platform/search?q=classytags) are the results- and didn't find anything. So are we sure this is being used?

**Comment by mariajgrimaldi** [comment] 2021-09-10 17:53
I left a comment earlier saying that this package was not being used. I was wrong. It's a dependency of `django-sekizai`, [here](https://github.com/edx/django-wiki/blob/b8cc9b026bf09b6f59b1e8bcecc4a9c17fc102d6/requirements/base.txt#L16) is the proof. 

For Django-classy-tags to support Django 3.2, we could modify their CI adding tests for that version. The problem is that the package depends on Django-cms support for Django 3.2, and it hasn't been released yet. So I'm gonna ask Django-cms's maintainers when they expect to make the release :)

**Comment by natabene** [comment] 2021-09-13 14:26
@mariajgrimaldi Thank you so much for an update, I appreciate.

**Comment by mariajgrimaldi** [comment] 2021-09-14 20:52
It's merged! I'll be posting when they make the new release.

**Comment by natabene** [comment] 2021-09-14 20:55
Great, thanks for an update, @mariajgrimaldi, I will be waiting for release news from you.

**Comment by mariajgrimaldi** [comment] 2022-01-24 21:07
Hey there. I've got good news! django-classy-tags has a new release! [v3.0.0](https://github.com/django-cms/django-classy-tags/commit/ab1d10e2cd50e8d58400b3cf9c87e39627357a21)

**Comment by natabene** [comment] 2022-01-25 02:01
@mariajgrimaldi  Thank you! Closing this issue. CC @Jawayria @awais786

**Closed by natabene** 2022-01-25 02:01 UTC
Labels: outdated dependency
