### ISSUE TITLE
Update or replace django-appconf

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#45] opened 2021-07-27 14:48 UTC
We use the package [django-appconf](https://github.com/django-compressor/django-appconf) in edx/course-discovery, edx/credentials, edx/ecommerce, edx/edx-analytics-dashboard, edx/edx-platform, edx/staff_graded-xblock. The last commit in this package's repo was made in 2020 and it hasn't yet added support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by jramnai** [comment] 2021-08-31 18:08
@jmbowman, this one is already tested against Django 3.2 but on Develop branch only. I have created [an issue](https://github.com/django-compressor/django-appconf/issues/83) for the new release.

**Comment by carltongibson** [comment] 2021-08-31 18:09
Did you try updating, and run the edX test suite? Were there failures? If not then you're good to go, but you really should test first.

**Comment by jramnai** [comment] 2021-09-01 15:25
I haven't tried to run the edX test suite with the updated package but the following is the reason we are looking for the version bump:
If Django 3.2 support has only been confirmed on the main development branch and a new release isn't imminent, figure out if we can continue using the latest release or have to update all our requirements files to install from source control instead (which is slower and forces us to later figure out when it's safe to go back to a PyPI release).

@jmbowman, correct me if I am wrong anywhere.

**Comment by natabene** [comment] 2021-09-02 02:49
@jramnai Thank you for looking into this, I will assign to you. @jmbowman Anything you want to add?

**Comment by natabene** [comment] 2021-09-15 17:12
Looks like we are waiting for end of September, see https://github.com/django-compressor/django-appconf/issues/83#issuecomment-919849078

**Comment by carltongibson** [comment] 2021-09-15 17:42
Django 4.0a will be next week. 


But there are no relevant code changes in AppConf. It's already compatible. 

You're holding yourselves up over packaging metadata. 

Did you run it against the EdX test suite?

**Comment by jramnai** [comment] 2021-09-25 08:25
Thanks @carltongibson for the new release.

@natabene, the new version is released on PyPI, I guess we can close this issue.

**Comment by natabene** [comment] 2021-09-27 14:31
@carltongibson @jramnai Thank you both.

**Closed by natabene** 2021-09-27 14:31 UTC
Labels: outdated dependency, edx/ecommerce
